<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<PackageId>zlib.net-mutliplatform</PackageId>
	<Product>zlib.net</Product>
	<Description>ZLIB.NET is a 100% managed version of ZLIB compression library which implements deflate and inflate compression algorithms.</Description>
	<Copyright>Copyright © 2006-2007, ComponentAce, 2022-2025 Sjofn LLC</Copyright>
	<AssemblyTitle>zlib.net</AssemblyTitle>
	<Version>1.1.0</Version>
	<Company>ComponentAce</Company>
  <Authors>cinderblocks</Authors>
  <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
  <DebugType>portable</DebugType>
  <AssemblyName>zlib.net</AssemblyName>
	<PackageTags>zlib;deflate;compression</PackageTags>
	<PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  <PackageProjectUrl>https://github.com/cinderblocks/zlib.net</PackageProjectUrl>
  <RepositoryType>git</RepositoryType>
  <RepositoryUrl>https://github.com/cinderblocks/zlib.net.git</RepositoryUrl>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  <IncludeSymbols>true</IncludeSymbols>
  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
	<None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**/obj/**" />
    <Compile Remove="**/bin/**" />
  </ItemGroup>
</Project>
